pub const RAYDIUM_LP_V4_PROGRAM_ID: &str = "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8";
pub const RAYDIUM_INSTRUCTION_SUCCESSFUL_CREATION_NEW_LP: &'static str = "Program 675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8 success";
pub const RAYDIUM_INSTRUCTION_CREATE_NEW_LP: &'static str = "initialize2";